use anyhow::Result;
use anyhow::anyhow;
use anyhow::bail;
use bitcoin::Amount;
use bitcoin::Txid;
use bitcoin::hashes::Hash;
use futures::StreamExt;
use hashi::config::HashiIds;
use hashi_types::move_types::DepositConfirmedEvent;
use hashi_types::move_types::DepositRequestedEvent;
use std::time::Duration;
use sui_crypto::SuiSigner;
use sui_crypto::ed25519::Ed25519PrivateKey;
use sui_rpc::field::FieldMask;
use sui_rpc::field::FieldMaskUtil;
use sui_rpc::proto::sui::rpc::v2::BatchGetObjectsRequest;
use sui_rpc::proto::sui::rpc::v2::Checkpoint;
use sui_rpc::proto::sui::rpc::v2::ExecuteTransactionRequest;
use sui_rpc::proto::sui::rpc::v2::GetBalanceRequest;
use sui_rpc::proto::sui::rpc::v2::GetObjectRequest;
use sui_rpc::proto::sui::rpc::v2::SubscribeCheckpointsRequest;
use sui_sdk_types::Address;
use sui_sdk_types::Argument;
use sui_sdk_types::GasPayment;
use sui_sdk_types::Identifier;
use sui_sdk_types::Input;
use sui_sdk_types::MoveCall;
use sui_sdk_types::ObjectReference;
use sui_sdk_types::ProgrammableTransaction;
use sui_sdk_types::SharedInput;
use sui_sdk_types::SplitCoins;
use sui_sdk_types::StructTag;
use sui_sdk_types::Transaction;
use sui_sdk_types::TransactionExpiration;
use sui_sdk_types::TransactionKind;
use sui_sdk_types::bcs::FromBcs;
use sui_sdk_types::bcs::ToBcs;
use tracing::debug;
use tracing::info;

use crate::TestNetworks;

fn txid_to_address(txid: &Txid) -> Address {
    let bytes: [u8; 32] = *txid.as_byte_array();
    Address::new(bytes)
}

/// Create a deposit request on Sui.
///
/// This function:
/// 1. Creates a UTXO object (txid, vout, amount, derivation_path)
/// 2. Creates a DepositRequest using the Clock
/// 3. Splits SUI for the deposit fee (if needed)
/// 4. Calls the deposit() function on Hashi
///
/// Returns the deposit request ID (a unique address generated by the transaction context).
pub async fn create_deposit_request_on_sui(
    sui_client: &mut sui_rpc::Client,
    hashi_ids: HashiIds,
    user_key: &Ed25519PrivateKey,
    txid: Txid,
    vout: u32,
    amount_sats: u64,
    derivation_path: Option<Address>,
) -> Result<Address> {
    let sender = user_key.public_key().derive_address();
    let price = sui_client.get_reference_gas_price().await?;

    info!(
        "Creating deposit request: txid={}, vout={}, amount={} sats, derivation_path={:?}",
        txid, vout, amount_sats, derivation_path
    );

    // Get Hashi and Clock shared objects
    let system_objects = sui_client
        .ledger_client()
        .batch_get_objects(
            BatchGetObjectsRequest::default()
                .with_requests(vec![
                    GetObjectRequest::new(&hashi_ids.hashi_object_id),
                    GetObjectRequest::new(&Address::from_static("0x6")), // Clock
                ])
                .with_read_mask(FieldMask::from_str("*")),
        )
        .await?
        .into_inner();
    let hashi_obj = system_objects.objects[0].object();
    let clock_obj = system_objects.objects[1].object();

    // Build the transaction inputs
    let txid_input = Input::Pure(txid_to_address(&txid).to_bcs()?);
    let vout_input = Input::Pure(vout.to_bcs()?);
    let amount_input = Input::Pure(amount_sats.to_bcs()?);
    let derivation_path_input = Input::Pure(derivation_path.to_bcs()?);

    // Deposit fee is 0 by default (see config.move:122)
    // We still need to provide a Coin<SUI>, so we'll split 0 from gas
    let zero_input = Input::Pure(0u64.to_bcs()?);

    let pt = ProgrammableTransaction {
        inputs: vec![
            Input::Shared(SharedInput::new(
                hashi_obj.object_id().parse()?,
                hashi_obj.owner().version(),
                true, // mutable
            )),
            Input::Shared(SharedInput::new(
                clock_obj.object_id().parse()?,
                clock_obj.owner().version(),
                false, // immutable
            )),
            txid_input,
            vout_input,
            amount_input,
            derivation_path_input,
            zero_input,
        ],
        commands: vec![
            // 1. Create UtxoId: utxo::utxo_id(txid, vout)
            sui_sdk_types::Command::MoveCall(MoveCall {
                package: hashi_ids.package_id,
                module: Identifier::from_static("utxo"),
                function: Identifier::from_static("utxo_id"),
                type_arguments: vec![],
                arguments: vec![Argument::Input(2), Argument::Input(3)],
            }),
            // Result(0) = UtxoId

            // 2. Create Utxo: utxo::utxo(utxo_id, amount, derivation_path)
            sui_sdk_types::Command::MoveCall(MoveCall {
                package: hashi_ids.package_id,
                module: Identifier::from_static("utxo"),
                function: Identifier::from_static("utxo"),
                type_arguments: vec![],
                arguments: vec![
                    Argument::Result(0), // UtxoId from previous call
                    Argument::Input(4),  // amount
                    Argument::Input(5),  // derivation_path
                ],
            }),
            // Result(1) = Utxo

            // 3. Create DepositRequest: deposit_queue::deposit_request(utxo, clock, ctx)
            sui_sdk_types::Command::MoveCall(MoveCall {
                package: hashi_ids.package_id,
                module: Identifier::from_static("deposit_queue"),
                function: Identifier::from_static("deposit_request"),
                type_arguments: vec![],
                arguments: vec![
                    Argument::Result(1), // Utxo from previous call
                    Argument::Input(1),  // Clock
                ],
            }),
            // Result(2) = DepositRequest

            // 4. Split zero SUI for fee coin: split_coins(gas, [zero])
            sui_sdk_types::Command::SplitCoins(SplitCoins {
                coin: Argument::Gas,
                amounts: vec![Argument::Input(6)],
            }),
            // Result(3) = vector<Coin<SUI>> with one coin of 0 balance
            // Use NestedResult(3, 0) to access the first coin

            // 5. Call deposit(hashi, request, fee)
            sui_sdk_types::Command::MoveCall(MoveCall {
                package: hashi_ids.package_id,
                module: Identifier::from_static("deposit"),
                function: Identifier::from_static("deposit"),
                type_arguments: vec![],
                arguments: vec![
                    Argument::Input(0),           // Hashi
                    Argument::Result(2),          // DepositRequest
                    Argument::NestedResult(3, 0), // fee Coin<SUI> (first element from SplitCoins)
                ],
            }),
        ],
    };

    let gas_objects = sui_client
        .select_coins(&sender, &StructTag::sui().into(), 1_000_000_000, &[])
        .await?;

    let transaction = Transaction {
        kind: TransactionKind::ProgrammableTransaction(pt),
        sender,
        gas_payment: GasPayment {
            objects: gas_objects
                .iter()
                .map(|o| -> Result<ObjectReference> { Ok((&o.object_reference()).try_into()?) })
                .collect::<Result<Vec<_>>>()?,
            owner: sender,
            price,
            budget: 1_000_000_000,
        },
        expiration: TransactionExpiration::None,
    };

    let signature = user_key.sign_transaction(&transaction)?;

    let response = sui_client
        .execute_transaction_and_wait_for_checkpoint(
            ExecuteTransactionRequest::new(transaction.into())
                .with_signatures(vec![signature.into()])
                .with_read_mask(FieldMask::from_str("*")),
            Duration::from_secs(10),
        )
        .await?
        .into_inner();

    if !response.transaction().effects().status().success() {
        bail!(
            "Deposit request transaction failed: {:?}",
            response.transaction().effects().status()
        );
    }

    let events = response.transaction().events();
    for event in events.events() {
        let event_type = event.contents().name();
        debug!("Event type: {}", event_type);

        // Look for DepositRequestedEvent
        if event_type.contains("DepositRequestedEvent") {
            let event_data = DepositRequestedEvent::from_bcs(event.contents().value())?;
            info!("Extracted request_id: {}", event_data.request_id);
            return Ok(event_data.request_id);
        }
    }

    Err(anyhow!(
        "DepositRequestedEvent not found in transaction events"
    ))
}

pub async fn wait_for_deposit_confirmation(
    sui_client: &mut sui_rpc::Client,
    request_id: Address,
    timeout: Duration,
) -> Result<()> {
    info!(
        "Waiting for deposit confirmation for request_id: {}",
        request_id
    );

    let start = std::time::Instant::now();
    let subscription_read_mask = FieldMask::from_paths([Checkpoint::path_builder()
        .transactions()
        .events()
        .events()
        .contents()
        .finish()]);
    let mut subscription = sui_client
        .subscription_client()
        .subscribe_checkpoints(
            SubscribeCheckpointsRequest::default().with_read_mask(subscription_read_mask),
        )
        .await?
        .into_inner();

    while let Some(item) = subscription.next().await {
        // Check timeout
        if start.elapsed() > timeout {
            return Err(anyhow!(
                "Timeout waiting for deposit confirmation after {:?}",
                timeout
            ));
        }

        let checkpoint = match item {
            Ok(checkpoint) => checkpoint,
            Err(e) => {
                debug!("Error in checkpoint stream: {}", e);
                continue;
            }
        };

        debug!(
            "Received checkpoint {}, checking for DepositConfirmedEvent...",
            checkpoint.cursor()
        );

        // Check all transactions in this checkpoint for DepositConfirmedEvent
        for txn in checkpoint.checkpoint().transactions() {
            for event in txn.events().events() {
                let event_type = event.contents().name();

                if event_type.contains("DepositConfirmedEvent") {
                    match DepositConfirmedEvent::from_bcs(event.contents().value()) {
                        Ok(event_data) => {
                            if event_data.request_id == request_id {
                                info!(
                                    "✓ Deposit confirmed! Found DepositConfirmedEvent for request_id: {}",
                                    request_id
                                );
                                return Ok(());
                            }
                        }
                        Err(e) => {
                            debug!("Failed to parse DepositConfirmedEvent: {}", e);
                        }
                    }
                }
            }
        }
        tokio::time::sleep(Duration::from_millis(100)).await; // Help avoid hanging in CI
    }

    Err(anyhow!("Checkpoint subscription ended unexpectedly"))
}

pub async fn get_hbtc_balance(
    sui_client: &mut sui_rpc::Client,
    package_id: sui_sdk_types::Address,
    owner: Address,
) -> Result<u64> {
    let btc_type = format!("{}::btc::BTC", package_id);
    let btc_struct_tag: StructTag = btc_type.parse()?;
    let request = GetBalanceRequest::default()
        .with_owner(owner.to_string())
        .with_coin_type(btc_struct_tag.to_string());

    let response = sui_client
        .state_client()
        .get_balance(request)
        .await?
        .into_inner();

    let balance = response.balance().balance_opt().unwrap_or(0);
    debug!("hBTC balance for {}: {} sats", owner, balance);
    Ok(balance)
}

pub fn lookup_vout(
    networks: &TestNetworks,
    txid: Txid,
    address: bitcoin::Address,
    amount: u64,
) -> Result<usize> {
    use bitcoincore_rpc::RpcApi;

    let tx = networks
        .bitcoin_node
        .rpc_client()
        .get_raw_transaction(&txid, None)?;
    let vout = tx
        .output
        .iter()
        .position(|output| {
            output.value == Amount::from_sat(amount)
                && output.script_pubkey == address.script_pubkey()
        })
        .ok_or_else(|| {
            anyhow!(
                "Could not find output with amount {} and deposit address",
                amount
            )
        })?;
    debug!("✓ Found deposit in tx output {}", vout);
    Ok(vout)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::TestNetworksBuilder;

    #[tokio::test]
    async fn test_bitcoin_deposit_e2e_flow() -> Result<()> {
        // Initialize tracing subscriber for test logs
        tracing_subscriber::fmt()
            .with_test_writer()
            .with_env_filter(
                tracing_subscriber::EnvFilter::from_default_env()
                    .add_directive(tracing::Level::INFO.into()),
            )
            .try_init()
            .ok();

        info!("=== Starting Bitcoin Deposit E2E Test ===");

        info!("Setting up test networks...");
        let mut networks = TestNetworksBuilder::new().with_nodes(4).build().await?;

        info!("✓ Test networks initialized");
        info!("  - Sui RPC: {}", networks.sui_network.rpc_url);
        info!("  - Bitcoin RPC: {}", networks.bitcoin_node.rpc_url());
        info!("  - Hashi nodes: {}", networks.hashi_network.nodes().len());

        let user_key = networks.sui_network.user_keys.first().unwrap();
        let hbtc_recipient = user_key.public_key().derive_address();
        let hashi = &networks.hashi_network.nodes()[0].0;
        let deposit_address =
            hashi.get_deposit_address(&hashi.get_hashi_pubkey(), Some(&hbtc_recipient));

        info!("Sending Bitcoin to deposit address...");
        let amount_sats = 31337u64;
        let txid = networks
            .bitcoin_node
            .send_to_address(&deposit_address, Amount::from_sat(amount_sats))?;
        info!("✓ Transaction sent: {}", txid);

        info!("Mining blocks for confirmation...");
        let blocks_to_mine = 10;
        networks.bitcoin_node.generate_blocks(blocks_to_mine)?;
        info!("✓ {blocks_to_mine} blocks mined");

        info!("Creating deposit request on Sui...");
        let vout = lookup_vout(&networks, txid, deposit_address, amount_sats)?;
        let request_id = create_deposit_request_on_sui(
            &mut networks.sui_network.client.clone(),
            networks.hashi_network.ids(),
            user_key,
            txid,
            vout as u32,
            amount_sats,
            Some(hbtc_recipient),
        )
        .await?;
        info!("✓ Deposit request created: {}", request_id);

        wait_for_deposit_confirmation(
            &mut networks.sui_network.client,
            request_id,
            Duration::from_secs(300),
        )
        .await?;
        info!("✓ Deposit confirmed on Sui");

        // Verify hBTC was minted to the recipient
        let hbtc_balance = get_hbtc_balance(
            &mut networks.sui_network.client,
            networks.hashi_network.ids().package_id,
            hbtc_recipient,
        )
        .await?;
        info!("✓ Recipient hBTC balance: {}", hbtc_balance);
        assert!(
            hbtc_balance == amount_sats,
            "Expected {} satoshis, got {}",
            amount_sats,
            hbtc_balance
        );

        info!("✓ Test completed successfully");
        Ok(())
    }
}
