[package]
name = "hashi-guardian"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
serde_bytes = "0.11.17"
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tonic.workspace = true
hashi-types = { path = "../hashi-types" }
hex.workspace = true

# Crypto dependencies
rand.workspace = true
bitcoin.workspace = true
k256.workspace = true
nsm_api = { git = "https://github.com/aws/aws-nitro-enclaves-nsm-api.git/", rev = "8ec7eac72bbb2097f1058ee32c13e1ff232f13e8", package="aws-nitro-enclaves-nsm-api", optional = false }
hpke.workspace = true

# AWS dependencies
aws-config.workspace = true
aws-sdk-s3.workspace = true
aws-credential-types.workspace = true
aws-smithy-http-client = { version = "1.1.12", features = ["rustls-aws-lc"] }
aws-smithy-runtime-api = { version = "1.11.6", features = ["client"] }

aws-smithy-mocks = { version = "0.1", optional = true }

[dev-dependencies]
hashi-types = { path = "../hashi-types", features = ["test-utils"] }
aws-sdk-s3 = { version = "1.12.0", features = ["test-util"] }
aws-smithy-mocks = "0.1"
tokio = { workspace = true, features = ["test-util"] }

[features]
# Stubs out the AWS Nitro NSM attestation call so the guardian can run
# outside a Nitro enclave and skips the Nitro hardware RNG startup check.
# Do not enable for prod builds. Also stubs the off-enclave verifier so it
# accepts the mock document.
non-enclave-dev = ["hashi-types/non-enclave-dev"]
# Exposes `test_utils` to external crates.
test-utils = ["dep:aws-smithy-mocks", "aws-sdk-s3/test-util", "hashi-types/test-utils"]
