name: Frontend CI

on:
  pull_request:
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Sui Binary
        run: .github/scripts/install-sui.sh

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json
      - run: pnpm --dir frontend install --frozen-lockfile

      - name: Check formatting
        run: make check-fmt-frontend

      - name: Codegen check
        run: |
          rm -rf frontend/packages/contracts/src
          make codegen
          make is-dirty
