name: gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RUSTFLAGS: -D warnings

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rustdoc
        run: make doc

      - uses: taiki-e/install-action@mdbook
      - name: build mdbook
        run: cd design && mdbook build

      - name: stage build artifacts
        run: |
          mkdir site
          mv ./target/doc site/rustdoc
          mv design/book site/design

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
